services:
    app:
        build:
            context: .
            dockerfile: ./docker/production/Dockerfile
        ports:
            - '${APP_PORT:-80}:80'
        volumes:
            - '.:/var/www/html'
