version: '2'

services:
  nginx:
    image: nginx
    container_name: 'nginx'
    ports:
      - '8080:80'
    volumes:
      - ../src:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

  php:
    build: ./php
    container_name: 'php'
    volumes:
      - ../src:/var/www
    working_dir: /var/www

  postgres:
    restart: always
    image: postgres:alpine
    container_name: 'postgres'
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - 15432:5432